name: 'Establish Context'
description: 'Establishes the context for the pipeline'
inputs:
  token:
    description: Token to use for Github API
    required: true
    default: ${{ github.token }}
  prerelease-branches:
    description: A comma-separated list of branch names that when merged a PR to will trigger a release.
    required: true
    default: ''
  environment-branch:
    description: If the build pipeline is for a target environment (e.g. development, test, staging) you'd specify that here.
    required: false
    default: ''
  current-version:
    description: If the version is known, you can specify it with this
    required: false
    default: ''
  version-file:
    description: If the version is in a file adhering to the expected JSON format, use this.
    required: false
    default: ''
  
outputs:
  should-publish:
    description: Whether or not the pipeline should publish
  current-version:
    description: The current version of the repository based on tags or 1.0.0 if there are no version tags
  release-type:
    description: The type of the release. One of [major, minor, patch, prerelease]
  cascading-release:
    description: Whether the publish was triggered by a cascading release.
  pr-body:
    description: The body of the pull request
  pr-url:
    description: The url to the pull request
  
runs:
  using: 'node16'
  main: 'release/index.js'