name: 'Establish Context'
description: 'Establishes the context for the pipeline'
inputs:
  token:
    description: Token to use for Github API
    default: ${{ github.token }}
  release-branches:
    description: |
      A list of the branches that should trigger a context establishment if a PR is merged against it.
      Give input as:
      with:
        release-branches: |
          main
          master
          ...
    default: |
      master
      main
      
  prerelease-branches:
    description: |
      A list of the prerelease branches that should trigger a prerelease context establishment if a PR is merged against it.
      Give input as:
      with:
        prerelease-branches: |
          main
          master
          ...
    default: ''
  environment-branch:
    description: If the build pipeline is for a target environment (e.g. development, test, staging) you'd specify that here.
    default: ''
  current-version:
    description: If the version is known, you can specify it with this
    default: ''
  version-file:
    description: If the version is in a file adhering to the expected JSON format, use this.
    default: ''
  
outputs:
  should-publish:
    description: Whether or not the pipeline should publish
  current-version:
    description: The current version of the context
  new-version:
    description: The new version of the context
  release-type:
    description: The type of the release. One of [major, minor, patch, prerelease]
  pr-body:
    description: The body of the pull request
  pr-url:
    description: The url to the pull request
  
runs:
  using: 'node16'
  main: 'release/index.js'