name: CI

on:
  push:
    branches:
    - '**'
    - '!main'
    - '!master'

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup node v16
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: yarn
      name: Install dependencies
    - run: yarn ci
      name: Build, Test and Lint
