name: CI

on:
  push:
    branches:
    - '**'
    - '!main'
    - '!master'

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - run: bun i
      name: Install dependencies
    - run: bun run ci
      name: Build, Test and Lint
