name: Establish Context and Release

on:
  pull_request:
    types: [closed]

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - run: bun i
      name: Install dependencies
    - run: bun run build
      name: Build local action
    - name: Establish context
      id: context
      uses: ./
    - name: Prepend to Changelog
      if: ${{ steps.context.outputs.should-publish == 'true' && steps.context.outputs.release-type != 'prerelease' }} 
      uses: woksin-org/add-to-changelog-action@v4
      with:
        version: ${{ steps.context.outputs.new-version }}
        body: ${{ steps.context.outputs.pr-body }}
        pr-url: ${{ steps.context.outputs.pr-url }}
    - name: Create GitHub Release
      if: ${{ steps.context.outputs.should-publish == 'true' }}
      uses: woksin-org/github-release-action@v3
      with:
        token: ${{  secrets.BUILD_PAT  }}
        version: ${{ steps.context.outputs.new-version }}
        body: ${{ steps.context.outputs.pr-body }}
