name: Establish Context and Release

on:
  pull_request:
    types: [closed]

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # Need to build this action to run it bellow
    - name: Setup node v16
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: yarn
      name: Install dependencies
    - run: yarn build
      name: Build local action
    - name: Establish context
      id: context
      uses: ./
    - name: Prepend to Changelog
      if: ${{ steps.context.outputs.should-publish == 'true' && steps.context.outputs.release-type != 'prerelease' }} 
      uses: woksin-org/add-to-changelog-action@v2
      with:
        version: ${{ steps.context.outputs.new-version }}
        body: ${{ steps.context.outputs.pr-body }}
        pr-url: ${{ steps.context.outputs.pr-url }}
    - name: Create GitHub Release
      if: ${{ steps.context.outputs.should-publish == 'true' }}
      uses: woksin-org/github-release-action@v2
      with:
        token: ${{  secrets.BUILD_PAT  }}
        version: ${{ steps.context.outputs.new-version }}
        body: ${{ steps.context.outputs.pr-body }}
